export const iconSet = {
  AntDesign: 'svgs/AntDesign.svg',
  Astro: 'svgs/Astro.svg',
  Axios: 'svgs/Axios.svg',
  NodeJS: 'svgs/NodeJS.svg',
  Element: 'svgs/Element.svg',
  React: 'svgs/React.svg',
  ReactRouter: 'svgs/ReactRouter.svg',
  Redux: 'svgs/Redux.svg',
  Sass: 'svgs/Sass.svg',
  SocketIO: 'svgs/SocketIO.svg',
  Solid: 'svgs/Solid.svg',
  TypeScript: 'svgs/TypeScript.svg',
  UnoCSS: 'svgs/UnoCSS.svg',
  Vite: 'svgs/Vite.svg',
  Vue: 'svgs/Vue.svg',
}
